name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ch01_06, ch07, ch08, ch09, ch10, ch11, ch12, ch13, ch15]

    steps:
      - uses: actions/checkout@v4

      - name: Format check
        working-directory: ${{ matrix.project }}
        run: cargo fmt --check

      - name: Cargo check
        working-directory: ${{ matrix.project }}
        run: cargo check --all-targets
