name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Format check (cargo fmt)
        run: cargo fmt --check

      - name: Syntax/type check (cargo check)
        run: cargo check --all-targets
